// Add a new month by pushing another { month: "...", winners: [...] } entry.
// Each winner supports: title, description, creators (array of {label, url}),
// code (Fortnite island code), playUrl (link to launch the island), image (thumbnail
// URL — leave null to show the "???" placeholder until artwork is ready), and
// comingSoon (true shows a "Coming Soon" badge in place of the Play button —
// once a real playUrl is added, that takes over automatically).

const SHOWCASE_MONTHS = [
  {
    month: "August 2026",
    winners: [
      {
        title: "One in the Chamber",
        description: "A One Shot, One Bullet game made by BombForge Studios.",
        creators: [{ label: "BombForge", url: "https://x.com/BombForge" }],
        code: "2102-2783-1506",
        playUrl: "https://www.fortnite.com/@bombforge/2102-2783-1506",
        image: "images/01-one-in-the-chamber.jpg",
      },
      {
        title: "Star Wars [Roguelike] Shadowfall",
        description: "A Creative roguelike set in Star Wars, built on lessons learned from every roguelike in the ecosystem.",
        creators: [{ label: "@kbuckmaster", url: "https://x.com/kbuckmaster" }],
        code: "2832-9803-9290",
        playUrl: "https://www.fortnite.com/@buckmaster/2832-9803-9290",
        image: "images/02-shadowfall.jpg",
      },
      {
        title: "Genesis Squid Game",
        description: "Makes an appearance for its first anniversary, with the host jumping into the game for the very first time!",
        creators: [{ label: "@GenesisStudios", url: "https://x.com/GenesisStudios" }],
        code: "5581-8600-6431",
        playUrl: "https://www.fortnite.com/@genesisstudios/5581-8600-6431",
        image: "images/03-genesis-squid-game.jpg",
      },
      {
        title: "Pirate Ship",
        description: "A showcase built in Fortnite Creative 1.0 — the talented modeller pulling the strings and making this amazing ship!",
        creators: [{ label: "@Puppetmasteer", url: "https://x.com/Puppetmasteer" }],
        code: null,
        playUrl: null,
        image: "images/04-pirate-ship.jpg",
      },
      {
        title: "Cosm & En",
        description: "Giving jumpscares and sleuthing around. Not yet published. PS: Touch Grass Gem lvl 500+.",
        creators: [{ label: "@SkylarGem", url: "https://x.com/SkylarGem" }],
        code: null,
        playUrl: null,
        image: "images/05-cosm-and-en.jpg",
      },
      {
        title: "Verity Pillars",
        description: "PS: also touch some grass, please.",
        creators: [{ label: "@JuliusSkull", url: "https://x.com/JuliusSkull" }],
        code: null,
        playUrl: null,
        comingSoon: true,
        image: "images/06-verity-pillars.jpg",
      },
      {
        title: "SawYair Gunfights",
        description: "Self-branding is a great idea — an amazing 4v4 gunfight map with great polish!",
        creators: [{ label: "@SawYair_", url: "https://x.com/SawYair_" }],
        code: "7001-0134-6677",
        playUrl: "https://www.fortnite.com/@sawyer/7001-0134-6677",
        image: "images/07-sawyair-gunfights.jpg",
      },
      {
        title: "🎲SUPER GAME OF PAIN🎲 BOARD GAME",
        description: "N3x7 u9 15 err0r c0d3 — glitching into the stream.",
        creators: [],
        code: "9981-0256-6722",
        playUrl: "https://www.fortnite.com/@bumpjumpergames/9981-0256-6722",
        image: "images/08-super-game-of-pain.jpg",
      },
      {
        title: "Snatching Sols",
        description: "Snatching Sols and making maps — currently in playtest, but already looking sick!",
        creators: [{ label: "@SOLdev_", url: "https://x.com/SOLdev_" }],
        code: "0464-6343-1343",
        playUrl: null,
        image: "images/09-snatching-sols.jpg",
      },
      {
        title: "DREAD",
        description: "A Genesis Studios community-showcased map makes two weekend appearances!",
        creators: [
          { label: "@GenesisStudios", url: "https://x.com/GenesisStudios" },
          { label: "@ReaperzUEFN", url: "https://x.com/ReaperzUEFN" },
        ],
        code: "9367-7868-6804",
        playUrl: null,
        comingSoon: true,
        image: "images/10-dread.jpg",
      },
      {
        title: "FBAK08 (3v3 Basketball)",
        description: "Shooting hoops in UEFN! Made by yt344567.",
        creators: [],
        code: "8662-5140-3879",
        playUrl: "https://www.fortnite.com/@yt344567/8662-5140-3879",
        image: "images/11-fbak08-basketball.jpg",
      },
      {
        title: "Alien Lab Tycoon",
        description: "From out of this world — take eggs, bring them back, and hatch them!",
        creators: [{ label: "@Elextris_FN", url: "https://x.com/Elextris_FN" }],
        code: "7373-0595-4789",
        playUrl: "https://www.fortnite.com/@elextris/7373-0595-4789",
        image: "images/12-alien-lab-tycoon.jpg",
      },
      {
        title: "Brainrot RNG 🎲🍀 (Simulator)",
        description: "Collect, equip, fight.",
        creators: [{ label: "@Ake_Studio_", url: "https://x.com/Ake_Studio_" }],
        code: "6982-6627-7196",
        playUrl: "https://www.fortnite.com/@akestudio/6982-6627-7196",
        image: "images/13-brainrot-rng.jpg",
      },
      {
        title: "BEAT THE BRAINROTS",
        description: "Still runs discovery — bringing it to the stream!",
        creators: [
          { label: "@PineFruitDev", url: "https://x.com/PineFruitDev" },
          { label: "@GetDillyApp", url: "https://x.com/GetDillyApp" },
        ],
        code: "1796-9956-7050",
        playUrl: "https://www.fortnite.com/@post/1796-9956-7050",
        image: "images/14-beat-the-brainrots.jpg",
      },
      {
        title: "Sunken Hope",
        description: "Got a sinking feeling — with awesome cinematics!",
        creators: [{ label: "@Giddybrommetje", url: "https://x.com/Giddybrommetje" }],
        code: "4665-3384-3482",
        playUrl: "https://www.fortnite.com/@giddybrom/4665-3384-3482",
        image: "images/15-sunken-hope.jpg",
      },
      {
        title: "🏆Better Egg Hunt 3: Reborn🥚🔍",
        description: "Had to keep you waiting — bigger, better... eggs.",
        creators: [{ label: "@WINXipde", url: "https://x.com/WINXipde" }],
        code: "7560-4645-2370",
        playUrl: "https://www.fortnite.com/@adiel0584/7560-4645-2370",
        image: "images/16-better-egg-hunt-3.jpg",
      },
      {
        title: "Bouncin Ballers",
        description: "In spirit, SpidaDan13YT gives his spot — balling out and rifting around!",
        creators: [{ label: "@CheezyCreates", url: "https://x.com/CheezyCreates" }],
        code: null,
        playUrl: null,
        image: "images/17-bouncin-ballers.jpg",
      },
      {
        title: "☁️ Sweaty Skies - Zone Wars",
        description: "Last call for the stream — sky domination and watching your step.",
        creators: [{ label: "@BenjiLikesCakes", url: "https://x.com/BenjiLikesCakes" }],
        code: "0996-3515-7339",
        playUrl: "https://www.fortnite.com/@cakesfn/0996-3515-7339",
        image: "images/18-sweaty-skies-zone-wars.jpg",
      },
    ],
  },
];